FROM alpine:latest

# 注入时区和证书
RUN apk add --no-cache ca-certificates tzdata

WORKDIR /app

ENV TZ=Asia/Shanghai
ENV RUNNING_IN_DOCKER=true

# 镜像描述标签
LABEL org.opencontainers.image.title="subs-check-pro" \
    org.opencontainers.image.description="高性能代理检测筛选工具，支持高并发测活、测速、媒体检测" \
    org.opencontainers.image.url="https://github.com/sinspired/subs-check-pro" \
    org.opencontainers.image.source="https://github.com/sinspired/subs-check-pro" \
    org.opencontainers.image.documentation="https://github.com/sinspired/subs-check-pro/wiki" \
    org.opencontainers.image.vendor="sinspired" \
    org.opencontainers.image.authors="Sinspired https://github.com/sinspired"

COPY subs-check-pro /app/subs-check-pro

EXPOSE 8199 8299

CMD ["/app/subs-check-pro"]